# <<: !include ../secrets.yaml

esphome:
  name: energy-monitor
  platform: ESP32
  board: mhetesp32devkit
  includes:
    - custom_components/energy_monitor
  libraries:
    - "https://github.com/anghel86/EmonLib-esp32.git#test"

wifi:
  # ssid: "anghel"
  # password: "formula1"
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.100.220
    gateway: 192.168.100.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Energy Monitor Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

esp32_ble_tracker:

sensor:
  - platform: custom
    lambda: |-
      auto custEnergyMonitor = new CustEnergyMonitor();
      App.register_component(custEnergyMonitor);
      return {custEnergyMonitor->volts_sensor, custEnergyMonitor->amps_sensor, custEnergyMonitor->watts_sensor};
    sensors:
      - name: "Voltage Sensor"
        unit_of_measurement: V
        # accuracy_decimals: 1
      - name: "Current Sensor"
        unit_of_measurement: A
        accuracy_decimals: 2
      - name: "Power Sensor"
        id: my_power
        unit_of_measurement: W
        accuracy_decimals: 0
        device_class: power
        state_class: measurement
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: my_power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kW
  - platform: xiaomi_lywsdcgq
    mac_address: "4C:65:A8:DC:29:97"
    temperature:
      name: "beed room temperature"
      filters:
        - median:
            window_size: 5
            send_every: 5
            send_first_at: 1
    humidity:
      name: "beed room humidity"
      filters:
        - delta: 0.2
    battery_level:
      name: "beed room battery"
      filters:
        - delta: 0.1

# Enable time component to reset energy at midnight
time:
  - platform: sntp
    id: my_time
    
# web_server:
#   port: 80
